# Generated by Django 4.0.6 on 2022-08-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to='blog.author'),
        ),
    ]
