# Generated by Django 4.0.6 on 2022-08-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='blog.author'),
        ),
    ]
