# Generated by Django 4.0.6 on 2022-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag_line',
            field=models.CharField(max_length=32),
        ),
    ]
