# Generated by Django 4.0.6 on 2023-12-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
