# Generated by Django 4.0.6 on 2023-12-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag_line',
            field=models.CharField(max_length=100),
        ),
    ]
