# Generated by Django 4.2.1 on 2024-01-07 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0010_alter_blog_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="author",
            name="name",
        ),
        migrations.AddField(
            model_name="author",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="author",
            name="github",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="instagram_profile",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="linkedin_channel",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="personal_website",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="author",
            name="stackoverflow",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="tagline",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="twitter_profile",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                default=59,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
