# Generated by Django 4.2.1 on 2024-01-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_remove_author_mail_remove_author_name_author_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to="blog.author"
            ),
        ),
    ]
