# Generated by Django 4.2.1 on 2024-01-08 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0014_userfollowing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollowing",
            unique_together={("user", "following_user")},
        ),
    ]
