# Generated by Django 4.2.1 on 2024-01-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_alter_userfollowing_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("genre", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="ebook_covers/"),
                ),
                ("language", models.CharField(max_length=50)),
                ("pages", models.PositiveIntegerField()),
                ("publisher", models.CharField(max_length=255)),
                ("availability", models.BooleanField(default=True)),
                ("average_rating", models.FloatField(default=0.0)),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                ("file", models.FileField(upload_to="ebooks/")),
                (
                    "file_format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("EPUB", "EPUB"), ("MOBI", "MOBI")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                    ),
                ),
            ],
        ),
    ]
